### ISSUE TITLE
apcusbd from brew, any hints? thanks!

### ISSUE THREAD

**Issue by mrose17** [droe/example.kext#2]
When running aptest:

	 libusb: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
	0.013 apcupsd: HidUps.cpp:174 Unable to claim interface (-13) Permission denied.

The brew install instructions are:

  	sudo cp -pR /usr/local/opt/apcupsd/Library/Extensions/ApcupsdDummy.kext /System/Library/Extensions/
  	sudo chown -R root:wheel /System/Library/Extensions/ApcupsdDummy.kext
  	sudo touch /System/Library/Extensions/

	Note: On OS X El Capitan and above, the kernel extension currently
	does not work as expected.

which doesn’t exactly inspire confidence (though I followed the steps).

I’ve followed the instructions in https://github.com/droe/example.kext#kext-installation … though these are out of date for Mojave, all you an do is "csrutil disable” to turn off “system integrity protection”…

**Comment by droe** [comment]
Cannot comment on the `ApcupsdDummy.kext` issue you are seeing, except that `/System/Library/Extensions/` is meant for Apple's kexts, not third-party kexts.

Regarding Mojave, have you tested that `csrutil enable --without kext` is not sufficient for loading `Example.kext`, but `csrutil disable` is? I do not have a Mojave box around for testing myself currently.

**Comment by mrose17** [comment]
thanks for the reply!

one of the frustrations in this situation is that no one seems to have all the answers. the folks who maintain the brew port of apcupsd give very specific instructions (above) followed by the "does not work as expected". others have parts of the puzzle, but not all. afaik, i'm the only person trying to get apcupsd to work on Mojave using the usb/modbus configuration.

please keep up the good work on the kext stuff!

/mtr

ps: i decided to solve this problem by throwing money at it, specifically a little add-on to the UPS that speaks SNMP. one of the amusing things about using APC gear is that each and every model seems to be purpose-built. the unit i have already has an RJ45 for ethernet, but it doesn't do SNMP...
